"""
bots/commit_explainer/bot.py
Weekly plain-English changelog generated by Claude.

Collects all commits from the last 7 days, builds a structured summary
(subject lines + changed files), and asks Claude to write a developer
changelog grouped by theme — what changed and why, no code review detail.
"""

from __future__ import annotations

from datetime import datetime, timedelta, timezone

import anthropic
import git

import re

import core.config as cfg
from core.logger import get_logger

log = get_logger("commit_explainer")

MODEL = "claude-haiku-4-5-20251001"
MAX_COMMITS = 100  # safety cap on repo walk
MAX_INPUT_CHARS = 8_000  # keeps prompt cost predictable

_STATE_FILE = cfg.DATA_DIR / "commit_explainer_last_sha.txt"
_CHANGELOG_FILE = cfg.DATA_DIR / "commit_explainer_latest.txt"
_SHA_RE = re.compile(r"^[0-9a-f]{40}$")

# Static instructions — cacheable system prompt; date range goes in the user message
SYSTEM_PROMPT = """\
You are a developer writing a concise weekly changelog for a software project.
You will be given a list of git commits: their dates, subject lines, and changed files.

Write a plain-English changelog that:
- Groups related changes into logical themes (e.g. "Bot improvements", "Dashboard", "Infrastructure")
- Summarises WHAT changed and WHY in clear language — avoid reproducing raw commit messages verbatim
- Uses past tense ("Added", "Fixed", "Improved", "Refactored")
- Keeps each entry to 1-2 sentences
- Omits trivial noise commits (typo fixes, formatting-only changes) unless there are no others

Response format:
## Weekly Changelog — {PERIOD}

### <Theme>
- <change>

If a week had no meaningful changes, say so in one sentence.\
"""


def _read_last_sha() -> str | None:
    if _STATE_FILE.exists():
        sha = _STATE_FILE.read_text().strip()
        return sha if _SHA_RE.match(sha) else None
    return None


def _write_last_sha(sha: str) -> None:
    _STATE_FILE.write_text(sha)


def _write_latest_changelog(text: str) -> None:
    _CHANGELOG_FILE.write_text(text, encoding="utf-8")


def _read_latest_changelog() -> str | None:
    if _CHANGELOG_FILE.exists():
        return _CHANGELOG_FILE.read_text(encoding="utf-8").strip() or None
    return None


def _get_weekly_commits() -> list[git.Commit]:
    """Return commits from the last 7 days, newest first."""
    repo = git.Repo(cfg.ROOT_DIR)
    since = datetime.now(timezone.utc) - timedelta(days=7)
    return [
        c
        for c in repo.iter_commits("HEAD", max_count=MAX_COMMITS)
        if datetime.fromtimestamp(c.committed_date, tz=timezone.utc) >= since
    ]


def _build_commit_summary(commits: list[git.Commit]) -> str:
    """
    Build a compact text summary of commits for the prompt.
    Uses commit stats (file names + line counts) — no diff content.
    """
    lines = []
    for c in commits:
        date = datetime.fromtimestamp(c.committed_date, tz=timezone.utc).strftime(
            "%Y-%m-%d"
        )
        subject = c.message.strip().splitlines()[0]

        try:
            files = list(c.stats.files.keys())
        except Exception:
            files = []

        files_str = ", ".join(files[:8])
        if len(files) > 8:
            files_str += f" (+{len(files) - 8} more)"

        lines.append(f"[{date}] {c.hexsha[:8]} {subject}")
        if files_str:
            lines.append(f"  → {files_str}")

    return "\n".join(lines)


def _call_claude(summary: str, date_range: str) -> tuple[str, str]:
    """Send the commit summary to Claude and return (changelog_body, token_footer)."""
    client = anthropic.Anthropic(api_key=cfg.ANTHROPIC_API_KEY)

    message = client.messages.create(
        model=MODEL,
        max_tokens=1024,
        system=[
            {
                "type": "text",
                "text": SYSTEM_PROMPT,
                "cache_control": {"type": "ephemeral"},
            }
        ],
        messages=[
            {
                "role": "user",
                "content": (f"Period: {date_range}\n\n" f"Commits:\n\n{summary}"),
            }
        ],
    )

    usage = message.usage
    cache_read = getattr(usage, "cache_read_input_tokens", 0)
    cache_write = getattr(usage, "cache_creation_input_tokens", 0)
    log.info(
        "Token usage — input: {} (cache_read: {} cache_write: {}) output: {}",
        usage.input_tokens,
        cache_read,
        cache_write,
        usage.output_tokens,
    )

    changelog = message.content[0].text.strip()

    footer = f"\n\n---\n*Model: `{MODEL}` · Tokens: {usage.input_tokens} in"
    if cache_read:
        footer += f" ({cache_read} cached)"
    footer += f" / {usage.output_tokens} out*"

    return changelog, footer


def run() -> str:
    """Entry point called by the BotRunner scheduler."""
    if not cfg.ANTHROPIC_API_KEY:
        raise EnvironmentError("ANTHROPIC_API_KEY is not set — add it to .env")

    log.info("Commit explainer starting")

    repo = git.Repo(cfg.ROOT_DIR)
    head_sha = repo.head.commit.hexsha

    if not _SHA_RE.match(head_sha):
        raise ValueError(f"Unexpected HEAD SHA format: {head_sha!r}")

    # No new commits since last run — skip Claude, resend cached changelog
    if head_sha == _read_last_sha():
        cached = _read_latest_changelog()
        if cached:
            log.info("No new commits since last run — resending cached changelog")
            return (
                "_No new commits since last changelog. Previous results below._"
                "\n\n---\n\n" + cached
            )
        log.info("No new commits and no cached changelog — nothing to send")
        return "No new commits since last run and no previous changelog on file."

    commits = _get_weekly_commits()
    if not commits:
        _write_last_sha(head_sha)
        return "No commits in the last 7 days — nothing to explain."

    log.info("Found {} commit(s) in the last 7 days", len(commits))

    summary = _build_commit_summary(commits)
    if len(summary) > MAX_INPUT_CHARS:
        summary = summary[:MAX_INPUT_CHARS].rsplit("\n", 1)[0]
        summary += "\n\n[truncated — too many commits to include in full]"
        log.warning("Commit summary truncated to {} chars", MAX_INPUT_CHARS)

    now = datetime.now(timezone.utc)
    date_range = (
        (now - timedelta(days=7)).strftime("%Y-%m-%d")
        + " to "
        + now.strftime("%Y-%m-%d")
    )

    changelog_body, footer = _call_claude(summary, date_range)
    log.info("Changelog generated for period {}", date_range)

    # Cache body only — token footer would be stale on repeat sends
    _write_last_sha(head_sha)
    _write_latest_changelog(changelog_body)

    return changelog_body + footer
